// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKbrbbUlySX_gch6PBo70FUG9Jyjfa0OM',
    appId: '1:916211298796:web:ceccde4de461d29663d0c9',
    messagingSenderId: '916211298796',
    projectId: 'true-time-provider',
    authDomain: 'true-time-provider.firebaseapp.com',
    storageBucket: 'true-time-provider.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEDW1ysaXbHg6mXyXJo58w9Y4SkwraSxU',
    appId: '1:916211298796:android:ce4cf80edaa4f11a63d0c9',
    messagingSenderId: '916211298796',
    projectId: 'true-time-provider',
    storageBucket: 'true-time-provider.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8koYVxNM85cTTLmbS1c0rZr3sCyQHjvY',
    appId: '1:916211298796:ios:75693bcd20ad862163d0c9',
    messagingSenderId: '916211298796',
    projectId: 'true-time-provider',
    storageBucket: 'true-time-provider.firebasestorage.app',
    iosBundleId: 'com.autoformsai.trueTimeProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8koYVxNM85cTTLmbS1c0rZr3sCyQHjvY',
    appId: '1:916211298796:ios:75693bcd20ad862163d0c9',
    messagingSenderId: '916211298796',
    projectId: 'true-time-provider',
    storageBucket: 'true-time-provider.firebasestorage.app',
    iosBundleId: 'com.autoformsai.trueTimeProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKbrbbUlySX_gch6PBo70FUG9Jyjfa0OM',
    appId: '1:916211298796:web:4baa1f6fd78e3f4063d0c9',
    messagingSenderId: '916211298796',
    projectId: 'true-time-provider',
    authDomain: 'true-time-provider.firebaseapp.com',
    storageBucket: 'true-time-provider.firebasestorage.app',
  );
}
